ALTER SESSION SET CURRENT_SCHEMA = SAMPLE;
SET DEFINE OFF;
SET SERVEROUTPUT ON;

DROP TABLE SAMPLE.DEPARTMENT;

CREATE TABLE SAMPLE.DEPARTMENT(
    DEPT_ID NUMBER(20,0),
    DEPT_NAME VARCHAR2(100 CHAR),
    CONSTRAINT DEPARTMENT_PK PRIMARY KEY (DEPT_ID)
);

GRANT SELECT, DELETE, INSERT, UPDATE ON SAMPLE.DEPARTMENT TO SAMPLE_RW_ROLE;
GRANT SELECT ON SAMPLE.DEPARTMENT TO SAMPLE_RO_ROLE;