ALTER SESSION SET CURRENT_SCHEMA = SAMPLE;
SET DEFINE OFF;
SET SERVEROUTPUT ON;

DROP TABLE SAMPLE.EMPLOYEE;

CREATE TABLE SAMPLE.EMPLOYEE(
    EMP_ID NUMBER(20,0),
    EMP_NAME VARCHAR2(100 CHAR),
    CONSTRAINT EMPLOYEE_PK PRIMARY KEY (EMP_ID)
);

GRANT SELECT, DELETE, INSERT, UPDATE ON SAMPLE.EMPLOYEE TO SAMPLE_RW_ROLE;